### GET all users
http://localhost:3000/users


### POST NEW BOOKS
POST http://localhost:3000/books/
Content-Type: application/json

{
    "BookID": 3,
    "Title": "Harry Potter and the Sorcerer's Stone",
    "Author": "J.K. Rowling",
    "ISBN": "9780747532699",
    "Genre": "Fantasy",
    "PublicationYear": 1997,
    "Availability": true,
    "Publisher": "Bloomsbury Pub Ltd"
}

### POST NEW LOANS

POST http://localhost:3000/loans/
Content-Type: application/json

{
    "LoanID": 3,
    "BookID": 3,
    "DateOut": "11/20/2024",
    "DueDate": "12/20/2024",
    "UserID": 2
}

### POST RESERVATION

POST http://localhost:3000/reservations/
Content-Type: application/json

{
    "ReservationID": 3, 
    "BookID": 3,
    "ReservationDate": "11/20/2024",
    "UserID": 1
}

### POST User
POST http://localhost:3000/users/
Content-Type: application/json

{
    "UserID": 3,
    "FirstName": "Emily",
    "LastName": "Whitney",
    "UserType": "staff",
    "MailingAddress": "123 Alphabet Dr. AnyCity, AnyState 12345" 
}